#!/bin/bash
LOGFILE=/tmp/hooroo_docker_install.log

function debug {
  if [[ ! -z "${DEBUG:-}" ]] && [[ "$DEBUG" == "true" ]]; then
    echo "[$(date)]: $*"
  fi
}

function log {
  echo "$*"
}

function silent_run {
  eval "$1 > /dev/null 2>&1"
}

function log_run {
  debug "$1"
  eval "$1 > $LOGFILE 2>&1"
  EVAL_EXIT_STATUS=$?
  return $EVAL_EXIT_STATUS
}

function check_for_docker_machine {
  log_run "docker-machine ls | grep dev"
}

function check_docker_works {
  log "Checking docker works"
  log_run "docker ps"
  if [[ $? -ne 0 ]]; then
    echo "Error during installation"
    exit 1
  fi
}

function create_docker_machine {
  log "Creating docker machine"
  check_for_docker_machine
  if [[ $? -ne 0 ]]; then
    log_run "docker-machine create --driver virtualbox dev"
    echo 'Consider adding eval "$(docker-machine env dev)" to your shell profile script'
    echo "Docker host is: $(docker-machine ip dev)"
  fi

  log_run "docker-machine start dev"
  eval "$(DEBUG=false docker-machine env dev)"
}

function install_hooroo_cert {
  log "Installing root certificate for Hooroo CA"
  # Install Hooroo Root Certificate into boot2docker
  log_run "bash <(curl -s https://gist.githubusercontent.com/dekz/4c2bd630df73d71c1a03/raw/add_custom_cert_to_boot2docker.sh)"
}

function pull_test_image {
  log "Pulling test image"
  log_run "docker pull docker-registry.in.jqdev.net/hooroo-base-alpine:latest"
}

function success {
  silent_run "curl -o /tmp/imgcat https://raw.githubusercontent.com/gnachman/iTerm2/master/tests/imgcat"
  silent_run "chmod +x /tmp/imgcat"
  silent_run "curl -o  /tmp/docker_install.png http://i.imgur.com/WQZRTjF.png"

  /tmp/imgcat /tmp/docker_install.png

  echo "Successfully installed"

}

log "Installing Outlaw..."
# Install latest docker and docker machine from Homebrew
log_run "brew install docker docker-machine"

create_docker_machine
check_docker_works
install_hooroo_cert
pull_test_image

success
